Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    
    config.vm.network "private_network", ip: "192.168.30.10"
    config.vm.network "forwarded_port", guest: 80, host:8080
    config.vm.network "forwarded_port", guest: 81, host:8081

    config.vm.provider "virtualbox" do |vb|
        vb.name = "01_hometask.vagrant.vm"
        vb.memory = "1024"
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install -y apache2 php
        wget https://raw.githubusercontent.com/NupaZzz/Hometasks/master/01-vagrant/1/index.php
        wget https://raw.githubusercontent.com/NupaZzz/Hometasks/master/01-vagrant/1/index.html
        mv index.php index.html /var/www/html/
        echo "<VirtualHost *:81>
        ServerAdmin webmaser@localhost
        DocumentRoot /var/www/html/index.php
</VirtualHost>">> /etc/apache2/sites-enabled/000-default.conf
        echo "Listen 81">> /etc/apache2/ports.conf
        systemctl restart apache2
    SHELL

    config.vm.provision "file", run: "always", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    config.vm.provision "file", run: "always", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
end