Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"

    config.vm.network "private_network", ip: "192.168.30.10"
    config.vm.network "forwarded_port", guest: 80, host:8080

    config.vm.provider "virtualbox" do |vb|
        vb.name = "01_hometask.vagrant.vm"
        vb.memory = "1024"
    end

    config.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install -y apache2 php
    SHELL

    config.vm.provision "file", run: "always", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    config.vm.provision "file", run: "always", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
end