jenkins_package_state: present
jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
jenkins_hostname: http://192.168.30.10:8080
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"
jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_init_folder: "/lib/systemd/system/jenkins.service"
jenkins_plugins_install_dependencies: true
jenkins_plugin_updates_expiration: 86400
jenkins_plugins:
  - credentials-binding
  - credentials
  - plain-credentials
  - git-client
  - ssh-credentials
  - workflow-scm-step
  - pipeline
  - publish-over-ssh
  - SSH Credentials Plugin
  - sshd
  - ssh-slaves
  - timestamper
  - golang
  - locale
  - ws-cleanup
  - git
  - nexus-artifact-uploader
  - configuration-as-code
  - Maven Integration Plugin
  - JUnit Plugin
  - SonarQube Plugin
  - Python