jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
       - id: ${NEXUS_ID}
         password: ${NEXUS_PASS}
unclassified:
  location:
    url: http://localhost:8080/