---
version: '3.3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "8080:8080"
    depends_on:
      - nexus
  nexus:
    build:
      context: .
      dockerfile: Dockerfile.nexus
      args:
        - username=nexus
        - password=nexus
    ports:
      - "8081:8081"