---
version: '3.3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - "80:8080"
    depends_on:
      - nexus

  nexus:
    build:
      context: .
      dockerfile: Dockerfile.nexus
    ports:
      - "81:8081"
