- name: master
  hosts: master
  gather_facts: false
  tasks:
    - name: add puppetserver rep
      become: yes
      dnf:
        name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm  
        state: present
        disable_gpg_check: true
    
    - name: install puppetserver
      become: yes
      dnf:
        name: puppetserver
        state: present
    
    - name: get puppet config
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/NupaZzz/Hometasks/master/03-puppet/puppetserver
        dest: /etc/sysconfig/
        mode: '0664'

    - name: restart ppserver
      become: yes
      service:
        name: puppetserver
        state: started

    - name: open port
      become: yes
      firewalld:
        port: 8140
        permanent: true
        state: enabled

- name: slave
  hosts: slave
  gather_facts: false
  tasks:
    - name: add puppetserver rep
      become: yes
      dnf:
        name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm  
        state: present
        disable_gpg_check: true
    
    - name: install puppet agent
      become: yes
      dnf:
        name: puppet-agent
        state: present
    
    - name: rework hosts
      lineinfile:
        path: /etc/hosts
        line: "192.168.30.10 master master"
        state: present

    - name: open port
      become: yes
      firewalld:
        port: 8140
        permanent: true
        state: enabled



