- name: master
  hosts: master
  gather_facts: false
  tasks:
    - name: Touch the file
      file:
        path: '{{ item.fpath }}'
        state: file
        owner: vagrant
        mode: u+rw,g-rwx,o-rwx
      loop:
        - { fpath: /home/vagrant/private_key_slave1 }
        - { fpath: /home/vagrant/private_key_slave2 }
        # - { fpath: /home/vagrant/private_key_mineserver }

    - name: add puppet rep
      become: yes
      dnf:
        name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm  
        state: present
        disable_gpg_check: true
    
    - name: install puppet and git
      become: yes
      dnf:
        name: [ 'puppetserver', 'git']
        state: present
    
    - name: get puppet config
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/NupaZzz/Hometasks/master/03-puppet/puppetserver
        dest: /etc/sysconfig/
        mode: '0755'

    - name: get puppet config
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/NupaZzz/Hometasks/master/03-puppet/puppet.conf
        dest: /etc/puppetlabs/puppet/puppet.conf
        mode: '0755'

    - name: add autosign
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/NupaZzz/Hometasks/master/03-puppet/autosign.conf
        dest: /etc/puppetlabs/puppet/autosign.conf
        mode: '0755'

    - name: install r10k
      become: yes
      shell: sudo /opt/puppetlabs/puppet/bin/gem install r10k

    - name: create r10k dir
      become: yes
      file:
        path: /etc/puppetlabs/r10k
        state: directory
        mode: '0755'

    - name: get r10k.yaml
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/NupaZzz/Hometasks/master/03-puppet/r10k.yaml
        dest: /etc/puppetlabs/r10k/r10k.yaml
        mode: '0755'

    - name: open port
      become: yes
      firewalld:
        zone: public
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - "80/tcp"
        - "8140/tcp"
        - "8081/tcp"
        - "8080/tcp"
        - "8082/tcp"
    
    - name: restart firewalld
      become: yes
      service:
        name: firewalld
        state: restarted

    - name: start ppserver
      become: yes
      service:
        name: puppetserver
        state: started
<<<<<<< HEAD
    
    - name: start puppet
      become: yes
      service:
        name : puppet
        state: started  
    
    - name: run r10k
      become: yes
      shell: sudo /opt/puppetlabs/puppet/bin/r10k deploy environment -p 

    - name: install puppet wget
      become: yes
      shell: sudo /opt/puppetlabs/bin/puppet module install maestrodev-wget

    - name: install puppet nginx
      become: yes
      shell: sudo /opt/puppetlabs/bin/puppet module install puppet-nginx --version 5.0.0

    - name: get bug solution
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/NupaZzz/Hometasks/master/03-puppet/script.py
        dest: /home/vagrant/
        mode: "0777"

    - name: run bug solution
      become: yes
      shell: sudo python3 /home/vagrant/script.py

    - name: off selinux
      become: yes
      shell: sudo setenforce 0
=======

    - name: run r10k
      become: yes
      shell: sudo /opt/puppetlabs/puppet/bin/r10k deploy environment -p   
    
    - name: isntall puppet wget
      become: yes
      shell: sudo /opt/puppetlabs/bin/puppet module install maestrodev-wget
>>>>>>> master
    

- name: slave
  hosts: slave
  gather_facts: false
  tasks:
    - name: add puppetserver rep
      become: yes
      dnf:
        name: https://yum.puppet.com/puppet7-release-el-8.noarch.rpm  
        state: present
        disable_gpg_check: true
    
    - name: install puppet agent
      become: yes
      dnf:
        name: puppet-agent
        state: present
    
    - name: rework hosts
      become: yes
      lineinfile:
        path: /etc/hosts
        line: "192.168.30.10 master"
        state: present
    
    - name: get puppet config
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/NupaZzz/Hometasks/master/03-puppet/puppet.conf
        dest: /etc/puppetlabs/puppet/puppet.conf
        mode: '0664'

    - name: open port 8140
      become: yes
      firewalld:
        zone: public
        port: 8140/tcp
        permanent: true
        state: enabled

<<<<<<< HEAD
    - name: open port
      become: yes
      firewalld:
        zone: public
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - "80/tcp"
        - "8140/tcp"
        - "8081/tcp"
        - "8080/tcp"
        - "8082/tcp"
=======
    - name: open port 80
      become: yes
      firewalld:
        zone: public
        port: 80/tcp
        permanent: true
        state: enabled
>>>>>>> master
    
    - name: restart firewalld
      become: yes
      service:
        name: firewalld
        state: restarted

    - name: start ppserver
      become: yes
      service:
        name: puppet
        state: started

    - name: get bug solution
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/NupaZzz/Hometasks/master/03-puppet/script.py
        dest: /home/vagrant/
        mode: "0777"

    - name: run bug solution
      become: yes
      shell: sudo python3 /home/vagrant/script.py
<<<<<<< HEAD

    - name: off selinux
      become: yes
      shell: sudo setenforce 0
=======
>>>>>>> master
