Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8s"
    config.vm.synced_folder ".", "/vagrant", disabled: false

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.name = "puppet"
    end

    config.vm.define "master", primary: true do |master|
        master.vm.network "private_network", ip: "192.168.30.10"
        master.vm.hostname = "master"
        master.vm.provider("virtualbox") { |vb| vb.memory = 1024 }
        master.vm.provision :shell, inline:<<-SHELL
            yum install -y python36-devel.x86_64 gcc libffi-devel openssl-devel curl
            sudo python3 -m pip install --upgrade pip   
        SHELL
        master.vm.provision :shell, privileged: false, inline:<<-SHELL
            python3 -m pip install cryptography --user --upgrade
            python3 -m pip install setuptools --user --upgrade
            python3 -m pip install python-dev-tools --user --upgrade
            python3 -m pip install ansible --user --upgrade
        SHELL
        master.vm.provision :ansible_local do |ansible|
            ansible.install_mode = :pip3
            ansible.verbose = "v"
            ansible.compatibility_mode = "2.0"
            ansible.playbook = "playbook.yaml"
            ansible.pip_install_cmd = "curl -s https://bootstrap.pypa.io/pip/get-pip.py | sudo python3"
            ansible.inventory_path = "inventory"
            ansible.limit = "all"
        end
    end
end