- name: Configure jenkins
  hosts: jenkins
  become: true

  tasks:
    - name: apt
      apt:
        update_cache: yes
    
    - name: Install jenkins
      apt:
        name: jenkins
        state: present

    - name: Unlock jenkins
      lineinfile:
          path: /lib/systemd/system/jenkins.service
          regexp: '^Environment="JAVA_OPTS=-Djava.awt.headless=true'
          line: 'Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
      register: result_skip_startup_wizard

    - name: reload
      service:
        name: jenkins
        state: restarted

    - name: create dir /var/lib/jenkins/init.groovy.d
      file:
        path: /var/lib/jenkins/init.groovy.d/
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: get config user for jenkins
      get_url:
        url: https://raw.githubusercontent.com/NupaZzz/Hometasks/master/05-jenkins/user.groovy
        dest: /var/lib/jenkins/init.groovy.d/user.groovy

    - name: create user file
      file:
        path: /var/lib/jenkins/init.groovy.d/user.groovy
        state: file
        owner: root
        group: root
        mode: '0755'
        
    - name: install plugins
      jenkins_plugin:
        name: "{{ item.key }}"
        url: http://192.168.30.10:8080
        url_username: admin
        url_password: admin
      register: plugin_result
      until: plugin_result is success
      retries: 50
      delay: 5
      with_items:
        - {key: 'groovy'}
        - {key: 'git'}