Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.synced_folder  ".", "/vagrant", disabled: false
  
    config.vm.define "jenkins" do |jenkins|
      jenkins.vm.network "private_network", ip: "192.168.30.10"
      jenkins.vm.provider "virtualbox" do |vb|
          vb.name = "jenkins"
          vb.memory = "1024"
      end
      # jenkins.vm.provision :shell, inline: <<-SHELL
      #   curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | sudo tee \
      #   /usr/share/keyrings/jenkins-keyring.asc > /dev/null
      #   echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
      #   https://pkg.jenkins.io/debian binary/ | sudo tee \
      #   /etc/apt/sources.list.d/jenkins.list > /dev/null
      #   SHELL
      jenkins.vm.provision :ansible_local do |ansible|
        ansible.version = 'latest'
        ansible.install_mode = 'pip'
        ansible.inventory_path = 'inventory'
        ansible.playbook = 'playbook.yaml'
      end
    end
end