Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.synced_folder  ".", "/vagrant", disabled: false
    config.vm.provider ("virtualbox") do |vb|
        vb.memory = 1024
    end
    config.vm.define "nexus" do |nexus|
      nexus.vm.network "private_network", ip: "192.168.30.11"
      nexus.vm.provider ("virtualbox") { |vb| vb.memory = 768; vb.name = 'nexus' }
      nexus.vm.provision :ansible_local do |ansible|
        ansible.version = 'latest'
        ansible.install_mode = 'pip'
        ansible.inventory_path = 'inventory'
        ansible.playbook = 'playbook.yaml'
      end
    end
    config.vm.define "staging" do |staging|
      staging.vm.network "private_network", ip: "192.168.30.12"
      staging.vm.provider ("virtualbox") { |vb| vb.memory = 768; vb.name = 'staging' }
    end
    config.vm.define "production" do |production|
      production.vm.network "private_network", ip: "192.168.30.13"
      production.vm.provider ("virtualbox") { |vb| vb.memory = 768; vb.name = 'production' }
    end
    config.vm.define "jenkins" do |jenkins|
      jenkins.vm.network "private_network", ip: "192.168.30.10"
      jenkins.vm.provider ("virtualbox") { |vb| vb.memory = 768; vb.name = 'jenkins' }
      jenkins.vm.provision :file, source: '.vagrant/machines/nexus/virtualbox/private_key', destination: '/home/vagrant/private_key_nexus'
      jenkins.vm.provision :file, source: '.vagrant/machines/staging/virtualbox/private_key', destination: '/home/vagrant/private_key_staging'
      jenkins.vm.provision :file, source: '.vagrant/machines/production/virtualbox/private_key', destination: '/home/vagrant/private_key_production'
      jenkins.vm.provision :ansible_local do |ansible|
        ansible.version = 'latest'
        ansible.install_mode = 'pip'
        ansible.inventory_path = 'inventory'
        ansible.playbook = 'playbook.yaml'
      end
    end
  end
