- name: html
  hosts: html
  become: yes
  become_method: sudo
  tasks:
  - name: apt update
    apt:
      upgrade: yes
      update_cache: yes
  
  - name: install packageS
    package:
      name: ['apache2']

  - name: get config html
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/NupaZzz/Hometasks/master/02-ansible/config/index.html
      dest: /var/www/html/
      mode: '0775'
  
  - name: apache2 restart
    service:
      name: apache2
      state: restarted

- name: php
  hosts: php
  become: yes
  become_method: sudo
  tasks:
  - name: apt update
    apt:
      upgrade: yes
      update_cache: yes
  
  - name: install packageS
    package:
      name: ['apache2', 'php']
  
  - name: delete html
    ansible.builtin.file:
      path: /var/www/html/index.html
      state: absent

  - name: get config php
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/NupaZzz/Hometasks/master/02-ansible/config/index.php
      dest: /var/www/html/
      mode: '0775'
  
  - name: apache2 restart
    service:
      name: apache2
      state: restarted

- name: proxy
  hosts: proxy
  become: yes
  become_method: sudo
  tasks:
    - name: apt update
      apt:
        upgrade: yes
        update_cache: yes

    - name: ufw rules
      ufw:
        rule: "allow"
        port: "{{ item }}"
        proto: "tcp"
      with_items:
        - "22"
        - "80"
        - "8081"
        - "8080"
        - "8082"

    - name: ufw enabled
      ufw:
        state: "enabled"
        policy: "deny"
        logging: "on"
    
    - name: install packageS
      package:
        name: ['nginx']

    - name: get nginx config
      get_url:
        url: https://raw.githubusercontent.com/NupaZzz/Hometasks/master/02-ansible/config/default
        dest: /etc/nginx/sites-available/
        mode: '0775'
    
    - name: ngnix restart
      service:
        name: nginx
        state: restarted