Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.synced_folder  ".", "/vagrant", disabled: false

  config.vm.define "html" do |node|
    node.vm.network "private_network", ip: "192.168.30.10"
    node.vm.network "forwarded_port", guest: 80, host:8080
    node.vm.provider "virtualbox" do |vb|
        vb.name = "html"
        vb.memory = "1024"
    end
  end

  config.vm.define "php" do |node|
    node.vm.network "private_network", ip: "192.168.30.11"
    node.vm.network "forwarded_port", guest: 80, host:8081
    node.vm.provider "virtualbox" do |vb|
        vb.name = "php"
        vb.memory = "1024"
    end
  end
  config.vm.define "proxy" do |node|
    node.vm.network "private_network", ip: "192.168.30.12"
    node.vm.network "forwarded_port", guest: 80, host:8082
    node.vm.provider "virtualbox" do |vb|
        vb.name = "proxy"
        vb.memory = "1024"
    end
    node.vm.provision :file, source: '.vagrant/machines/html/virtualbox/private_key', destination: '/home/vagrant/private_key_html'
    node.vm.provision :file, source: '.vagrant/machines/php/virtualbox/private_key', destination: '/home/vagrant/private_key_php'
    node.vm.provision :shell, inline: <<-SHELL
        sudo chmod 0600 /home/vagrant/private_key_html
        sudo chmod 0600 /home/vagrant/private_key_php
    SHELL
    node.vm.provision "ansible_local" do |ansible|
      ansible.install_mode = "pip"
      ansible.version = "latest"
      ansible.playbook  = "playbook.yaml"
      ansible.limit = "all"
      ansible.inventory_path  = "inventory.ini"
    end 
  end
end
