Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-22.04"
    
    config.vm.network "private_network", ip: "192.168.30.10"
    config.vm.network "forwarded_port", guest: 80, host:8080
    config.vm.network "forwarded_port", guest: 81, host:8081

    config.vm.provider "virtualbox" do |vb|
        vb.name = "02_hometask.vagrant.vm"
        vb.memory = "1024"
    end

    config.vm.provision "ansible_local" do |ansible|
        ansible.limit= "all"
        ansible.install_mode = "pip"
        ansible.version = "latest"
        ansible.playbook = "provision.yaml"
    end
end