Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "bento/ubuntu-22.04"
    web.vm.network "private_network", ip: "192.168.30.20"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
    end
    web.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install -y apache2
        wget https://raw.githubusercontent.com/NupaZzz/Hometasks/master/01-vagrant/1/index.html
        mv /home/vagrant/index.html /var/www/html/
        systemctl restart apache2
    SHELL
  end

  config.vm.define "db" do |db|
    db.vm.box = "bento/ubuntu-22.04"
    db.vm.network "private_network", ip: "192.168.30.30"
    db.vm.network "forwarded_port", guest: 80, host: 8081
    db.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
    end
    db.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install -y apache2 php
        wget https://raw.githubusercontent.com/NupaZzz/Hometasks/master/01-vagrant/1/index.php
        rm /var/www/html/index.html
        mv /home/vagrant/index.php /var/www/html/
        echo "<VirtualHost *:8081>
        ServerAdmin webmaser@localhost
        DocumentRoot /var/www/html/index.php
</VirtualHost>">> /etc/apache2/sites-enabled/000-default.conf
        echo "Listen 8081">> /etc/apache2/ports.conf
        systemctl restart apache2
    SHELL
  end
end