Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
    web.vm.box = "bento/ubuntu-22.04"
    web.vm.network "private_network", ip: "192.168.33.20"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
    end
  end

  config.vm.define "db" do |db|
    db.vm.box = "bento/ubuntu-22.04"
    db.vm.network "private_network", ip: "192.168.33.30"
    db.vm.network "forwarded_port", guest: 80, host: 8080
    db.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
    end
  end
end