pipeline {
    agent any
    stages {
        stage('Checkout') {
             steps {
                git 'https://github.com/NupaZzz/word-cloud-generator.git'
            }
        }
        stage('Lint and Test') {
            steps {
                sh 'make lint'
                sh 'make test'
            }
        }
        stage('Build and Upload') {
            steps {
                sh 'make build'
            }
        }
    }
}
