---
- name: Install Jenkins plugins
  jenkins_plugin:
      name: "{{ item }}"
      url: "{{ jenkins_hostname }}"
      url_username: "{{ jenkins_admin_username }}"
      url_password: "{{ jenkins_admin_password }}"
      with_dependencies: "{{ jenkins_plugins_install_dependencies }}"
      updates_expiration: "{{ jenkins_plugin_updates_expiration }}"
  register: plugin_result
  until: plugin_result is success
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  with_items: "{{ jenkins_plugins }}"
      