apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{ .Values.container.label.key }}: {{ .Values.container.label.value }}
  ports:
    - protocol: {{ .Values.ports.name }}
      port: {{ .Values.ports.port }}
      targetPort: {{ .Values.ports.targetPort }}