name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: wcg
  OWNER: '${{ github.repository_owner.lowercase() }}'
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Print env
        run: echo "github_actor:=${{ github.actor }} repo_owner:= $REPO_OWNER  docker_tag:= $DOCKER_TAG"
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./07-docker
          file: ./07-docker/Dockerfile.multi
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
            ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:latest
        
