name: Build and Push Docker Image

on:
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: wcg
  DOCKER_TAG: ${{ github.sha }}
  OWNER: '${{ github.repository_owner }}'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./07-docker
          file: ./07-docker/Dockerfile.multi
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
            ghcr.io/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:latest

      - name: Create tag for new version
        if: github.ref == 'refs/heads/dev'
        run: |
          git config --global user.email "Nupalolz@gmail.com"
          git config --global user.name "NupaZzz"
          git tag -a v1.0.${{ github.run_number }} -m "Version 1.0.${{ github.run_number }}"
          git push origin --tags

      - name: Check Helm chart
        run: |
          helm lint ./12-helm
          helm lint -f ./12-helm/values.yaml
          
      - name: Package Helm chart
        run: helm package ./12-helm
