name: Build and Push Docker Image

on:
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: wcg
  DOCKER_TAG: ${{ github.sha }}
  OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Update Helm chart version
        run: |
          sed -i "s/version: .*/version: $(echo \"${{ steps.tag_version.outputs.new_tag }}\" | sed -e 's/\./\\./g')/" ./12-helm/Chart.yaml

      - name: Update Docker image tag in Helm chart
        run: |
          sed -i "s/tag: .*/tag: ${{ steps.tag_version.outputs.new_tag }}/" ./12-helm/values.yaml

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./07-docker
          file: ./07-docker/Dockerfile.multi
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
            ghcr.io/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:${{ steps.tag_version.outputs.new_tag }}

      - name: Check Helm chart
        run: |
          helm lint ./12-helm

      - name: Create package directroy
        run: mkdir package
        
      - name: Package Helm chart
        run: |
          helm package ./12-helm --destination ./package

      - name: Create Helm Repository
        run: |
          helm repo index .

      - name: Commit Changes
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com
        run: |
          git config --local user.email "${GIT_AUTHOR_EMAIL}"
          git config --local user.name "${GIT_AUTHOR_NAME}"
          git add .
          git commit -m "Update Helm repository"
          git push
          

        
